apiVersion: v1
kind: Service
metadata:
  name: nginx-project
  namespace: dev
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080    # External port
      targetPort: 80  # Container port
      name: http
  selector:
    app: nginx-project
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-project
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-project
  template:
    metadata:
      labels:
        app: nginx-project
    spec:
      containers:
        - name: nginx
          image: nginx:1.17.3
          ports:
            - containerPort: 80 # Container port